spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password : postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always


