spring:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password : postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
    include-binding-errors: always


